pipeline {
    agent any

    environment {
        IMAGE_NAME = "monitoring-app"
        TAG = "v1.${BUILD_NUMBER}"
        REPO = "Susan2018-collab/k8"
    }

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh """
                    docker build -t ${IMAGE_NAME}:${TAG} projects/monitoring-app
                """
            }
        }

        stage('Update Helm Chart') {
            steps {
                sh """
                    sed -i 's|tag:.*|tag: ${TAG}|g' projects/nginx-chart/values.yaml
                """
            }
        }

        stage('Commit & Push Changes') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'github-creds',
                    usernameVariable: 'GIT_USERNAME',
                    passwordVariable: 'GIT_TOKEN'
                )]) {
                    sh """
                        git config user.email "jenkins@example.com"
                        git config user.name "jenkins"

                        git add projects/nginx-chart/values.yaml
                        git commit -m "Update image tag to ${TAG}" || true

                        git push https://${GIT_USERNAME}:${GIT_TOKEN}@github.com/${REPO}.git HEAD:main
                    """
                }
            }
        }
    }

    post {
        success {
            echo "Pipeline SUCCESS"
        }
        failure {
            echo "Pipeline FAILED"
        }
    }
}
