apiVersion: v1
clusters:
- cluster:
    certificate-authority: /Users/susandaniel/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Wed, 25 Mar 2026 14:38:32 IST
        provider: minikube.sigs.k8s.io
        version: v1.38.1
      name: cluster_info
    server: https://127.0.0.1:62259
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Wed, 25 Mar 2026 14:38:32 IST
        provider: minikube.sigs.k8s.io
        version: v1.38.1
      name: context_info
    namespace: dev
    user: minikube
  name: minikube
current-context: minikube
kind: Config
users:
- name: minikube
  user:
    client-certificate: /Users/susandaniel/.minikube/profiles/minikube/client.crt
    client-key: /Users/susandaniel/.minikube/profiles/minikube/client.key
