apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: monitor-app
  template:
    metadata:
      labels:
        app: monitor-app
    spec:
      serviceAccountName: monitor-sa
      containers:
      - name: monitor-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5000
