apiVersion: v1
kind: Service
metadata:
  name: monitor-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: monitor-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      nodePort: 30008
