apiVersion: v1
kind: Secret
metadata:
  name: notifier-secret
type: Opaque
stringData:
  SLACK_WEBHOOK: "{{ .Values.env.slackWebhook }}"
  EMAIL_USER: "{{ .Values.env.emailUser }}"
  EMAIL_PASS: "{{ .Values.env.emailPass }}"
